### ISSUE TITLE
Unable to download given dataset

### ISSUE THREAD

**Issue by kini5gowda** [avasalya/Yolo6D_ROS#2]
Hi, I'm being asked a password to download the given dataset from the drive link.

**Comment by avasalya** [comment]
Hi @kini5gowda, the password-protected link is for the trained weights on our custom object, and it is available only to our internal team members. However, I have updated the readme with instructions on how to create and train on your own custom dataset. 
please check here,
[https://github.com/avasalya/Yolo6D_ROS#train-on-custom-dataset](https://github.com/avasalya/Yolo6D_ROS#train-on-custom-dataset)
 I hope you find it useful.
